### ISSUE TITLE
Migrating setup/teardown-scripts to deployment manager

### ISSUE THREAD

**Issue by Pindar** [Pindar/gcloud-k8s-express-app#2]
I was thinking about alternatives to my setup/teardown scripts. One was to use terraform #1 . The other solution might be to use deployment-manager. I was lucky enough to get the cluster created with [this example](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/examples/v2/gke) but I haven't seen any possibility in [their documentation](https://cloud.google.com/deployment-manager/docs/configuration/supported-resource-types) to create either a new project or to create service accounts.

If anyone knows how to deal with it please let me know. Otherwise I don't see the point to change the cluster deployment from a one-liner to a multi-file setup.

**Comment by Pindar** [comment]
from the output of `gcloud deployment-manager types list` it seems that iam.v1.serviceAccount is supported. 

```
resources:
- name: test-gitlabci-k8s-1
  type: iam.v1.serviceAccount
  properties:
    accountId: "gitlab-ci-token-1"
    displayName: "Account is used to deploy to Kubernetes from Gitlab CI"
```

works to create the service account but not to set Iam Policy. Has someone an example for me?
